version: '3.4'
services:

  #PHP Service
  app:
    image: learning-docker/laravel:v1
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  #Nginx Service
  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
 #MySQL Service
  db:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_hmvc
      MYSQL_USER: daochien
      MYSQL_PASSWORD: daochien@93
      MYSQL_ROOT_PASSWORD: rootpass
      SERVICE_NAME: mysql
    volumes:
      - .docker/data/db:/var/lib/mysql/
    ports:
        - "33061:3306"

